feature: sorting only added
BoBoBaSs84/DDS.Tools pull request #116
Opened 2024-11-08 15:41 UTC by Probotus

changes:
- [feat: various providers added](https://github.com/BoBoBaSs84/DDS.Tools/commit/e449ba5420149d9923e283b425833127c1701032)
- [feat: directory provider improved](https://github.com/BoBoBaSs84/DDS.Tools/commit/3019976e125e82eed555545231afe04b31170658)
- [feat: providers even more improved](https://github.com/BoBoBaSs84/DDS.Tools/commit/642f4c51fb0f1d8e3271ad400b5bacfa4454343c)
- [feat: commands improved](https://github.com/BoBoBaSs84/DDS.Tools/commit/4278a8fa49229db2784f2940e4a313bb11a7586a)
- [feat: enumerator added and todo service improved](https://github.com/BoBoBaSs84/DDS.Tools/commit/b30636246e132381e6c76c016f7f9c77a3f82229)
- [feat: unit tests added and fixed](https://github.com/BoBoBaSs84/DDS.Tools/commit/6f34d0149f35c787d7e5b420e9695b9c20c413fa)

closes #115

2024-11-09 09:01 UTC, BoBoBaSs84 commented
I have to Test this in depth manually ..

2024-11-09 17:14 UTC, BoBoBaSs84 requested changes
So far so good, it really should be named grouping.
The docs are missing, I'll open up a new issue for that.

2024-11-09 17:14 UTC, BoBoBaSs84 commented on src/DDS.Tools/Enumerators/ConvertModeType.cs
> +	Sorting = 2
Grouping?

2024-11-09 17:14 UTC, BoBoBaSs84 commented on src/DDS.Tools/Services/TodoService.cs
> +	private void MoveImage(ConvertSettingsBase settings, TodoModel todo, ImageType imageType)
Copy instead of move?

2024-11-09 17:14 UTC, BoBoBaSs84 commented on tests/DDS.ToolsTests/Services/TodoServiceTests.GetTodosDone.cs
> +	public void GetTodosDoneSortingTest()
Grouping?

2024-11-10 09:00 UTC, Probotus commented
I applied the changes.

2024-11-10 09:01 UTC, BoBoBaSs84 approved these changes

2024-11-10 09:05 UTC, merged